jdbc:
  driverClassName : org.postgresql.Driver
  password : 2Shop
  user : shopper
  url : jdbc:postgresql://localhost:5433/postgres

dbcp2:
  initialSize : 3
  lifo : false
  maxTotal : 6

cache:
  genre:
    refresh:
      # 1000 (ms) * 60 (sec) * 60 (min) * 4 (hours) = 14400000
      initialDelay : 14400000
      fixedDelay : 14400000

myScheduler:
  pool-size : 2

liquibase:
  autorun : true

currency:
  nativeCurrency : UAH
  cron : 01 0 16,18 ? * MON-FRI
  url : https://bank.gov.ua/NBUStatService/v1/statdirectory/exchange?json
